CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          product_status VARCHAR(50) NOT NULL
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT  AS IDENTITY  PRIMARY KEY ,
    product_id BIGINT NOT NULL ,
    product_name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL
)