DROP TABLE IF EXISTS promotion_required_products;
DROP TABLE IF EXISTS promotion_target_products;
DROP TABLE IF EXISTS promotions;

DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;


CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          product_status VARCHAR(50) NOT NULL
);


CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        status VARCHAR(50) NOT NULL,
                        created_at TIMESTAMP NOT NULL
);


CREATE TABLE order_items (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id BIGINT NOT NULL,
                             product_id BIGINT NOT NULL,
                             product_name VARCHAR(255) NOT NULL,

                             CONSTRAINT fk_order_items_order
                                 FOREIGN KEY (order_id)
                                     REFERENCES orders(id),

                             CONSTRAINT fk_order_items_product
                                 FOREIGN KEY (product_id)
                                     REFERENCES products(id)
);


CREATE TABLE promotions (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            created_at TIMESTAMP NOT NULL,

                            start_date TIMESTAMP NOT NULL,
                            end_date TIMESTAMP NOT NULL,

                            status VARCHAR(50) NOT NULL,
                            promotion_type VARCHAR(50) NOT NULL,

                            occurrences INT,
                            minimum_value INT,

                            reward_type VARCHAR(50) NOT NULL,
                            reward_value FLOAT
);


CREATE TABLE promotion_target_products (
                                           promotion_id BIGINT NOT NULL,
                                           product_id BIGINT NOT NULL,

                                           CONSTRAINT pk_promotion_target_products
                                               PRIMARY KEY (promotion_id, product_id),

                                           CONSTRAINT fk_promotion_target_products_promotion
                                               FOREIGN KEY (promotion_id)
                                                   REFERENCES promotions(id),

                                           CONSTRAINT fk_promotion_target_products_product
                                               FOREIGN KEY (product_id)
                                                   REFERENCES products(id)
);


CREATE TABLE promotion_required_products (
                                             promotion_id BIGINT NOT NULL,
                                             product_id BIGINT NOT NULL,

                                             CONSTRAINT pk_promotion_required_products
                                                 PRIMARY KEY (promotion_id, product_id),

                                             CONSTRAINT fk_promotion_required_products_promotion
                                                 FOREIGN KEY (promotion_id)
                                                     REFERENCES promotions(id),

                                             CONSTRAINT fk_promotion_required_products_product
                                                 FOREIGN KEY (product_id)
                                                     REFERENCES products(id)
);